spring:
  application:
    name: aibe-team2-api
  profiles:
    active: dev

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

server:
  # 기본값(로컬 개발용)
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

logging:
  level:
    root: INFO
    com.aibe.team2: DEBUG
    org.hibernate.SQL: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info
  health:
    redis:
      enabled: false

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

# 외부 API 및 인프라 공통 설정
gemini:
  api:
    key: ${GEMINI_API_KEY}
    url: ${GEMINI_API_URL}

retell:
  api:
    key: ${RETELL_API_KEY}
  agent:
    id: ${RETELL_AGENT_ID}

aws:
  region: ${AWS_REGION:ap-northeast-2}

  s3:
    bucket: aibe-bucket
    presign-expiration-minutes: 10
    allowed-content-types: application/pdf,image/png,image/jpeg

  sqs:
    {}

# JWT 관련 사용자 정의 설정 (JwtTokenProvider에서 불러다 쓸 용도)
jwt:
  # 충분히 긴 문자열(32자 이상)
  secret: your-256-bit-secret-key-must-be-very-long-and-random-string-here
  expiration-time: 86400000 # 토큰 만료 시간 (24시간)