spring:
  application:
    name: aibe-team2-api
  profiles:
    active: dev # 기본적으로 실행할 프로필을 dev로 지정

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

logging:
  level:
    root: INFO
    com.aibe.team2: DEBUG
    org.hibernate.SQL: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info
  health:
    redis:
      enabled: false

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

# 외부 API 및 인프라 공통 설정
gemini:
  api:
    key: ${GEMINI_API_KEY}
    url: ${GEMINI_API_URL}

retell:
  api:
    key: key_50c10277448c070f6b6bb6c2ecba
  agent:
    id: agent_28edb6c22201bee8f27a45ecfd

aws:
  sqs:
    endpoint: http://${LOCALSTACK_HOST:localhost}:${LOCALSTACK_PORT:4566}
    region: ${AWS_REGION:ap-northeast-2}