server:
  port: 8080
  forward-headers-strategy: framework

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST:db}:${POSTGRES_PORT:5432}/${POSTGRES_DB:aibe_team2}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${AUTH_ID}
    password: ${AUTH_PW}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:}
            client-secret: ${GOOGLE_CLIENT_SECRET:}
            scope:
              - email
              - profile
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-name: Google

          github:
            client-id: ${GITHUB_CLIENT_ID:}
            client-secret: ${GITHUB_CLIENT_SECRET:}
            scope:
              - user:email
              - read:user
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-name: GitHub

          kakao:
            client-id: ${KAKAO_CLIENT_ID:}
            client-secret: ${KAKAO_CLIENT_SECRET:}
            scope:
              - profile_nickname
#              - account_email // 카카오 개인 개발자는 해당 프로퍼티를 불러올 수 없음
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-name: Kakao
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: false

  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}

  batch:
    job:
      enabled: false

  cloud:
    aws:
      region:
        static: ${AWS_REGION}

management:
  endpoints:
    web:
      exposure:
        include: health,info


cors:
  allowed-origins: "https://synctalk.it.com, https://www.stnctalk.it.com"

app:
  frontend:
    oauth-redirect-uri: https://synctlk.it.com/oauth/callback
  error:
    alert:
      occurrence-threshold: 10