server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST:db}:${POSTGRES_PORT:5432}/${POSTGRES_DB:aibe_team2}
    username: ${POSTGRES_USER:root}
    password: ${POSTGRES_PASSWORD:password}

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: false

  data:
    redis:
      host: ${DOCKER_REDIS_HOST:redis}
      port: ${DOCKER_REDIS_PORT:6379}

aws:
  s3:
    endpoint: http://${LOCALSTACK_HOST:localstack}:${LOCALSTACK_PORT:4566}
  sqs:
    endpoint: http://${LOCALSTACK_HOST:localstack}:${LOCALSTACK_PORT:4566}